enum Role {
  Admin
  Manager
  Employee
}

enum Gender {
  Male
  Female
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  managerId: ID
  branchId: ID
  vendorId: ID
  userRole: Role!
  phoneNumber: String!
  designation: String!
  dateOfBirth: DateTime!
  dateOfJoining: DateTime!
  emergencyContactName: String!
  emergencyContactNumber: String!
  gender: Gender
  createAt: DateTime!
  updatedAt: DateTime!
  isDeleted: Boolean!
}

type AuthTokens {
  accessToken: String!
  refreshToken: String!
  tokenType: String!
  expiresIn: Int!
}

input RegisterInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  managerId: ID
  branchId: ID
  vendorId: ID
  userRole: Role!
  phoneNumber: String!
  designation: String!
  dateOfBirth: DateTime!
  dateOfJoining: DateTime!
  emergencyContactName: String!
  emergencyContactNumber: String!
  gender: Gender
}

input UpdateUserInput {
  firstName: String
  lastName: String
  email: String
  managerId: ID
  branchId: ID
  vendorId: ID
  userRole: Role
  phoneNumber: String
  designation: String
  dateOfBirth: DateTime
  dateOfJoining: DateTime
  emergencyContactName: String
  emergencyContactNumber: String
  gender: Gender
}

input LoginInput {
  email: String!
  password: String!
}

input RefreshTokenInput {
  refreshToken: String!
}

type UserListResponse {
  results: [User!]!
  totalCount: Int!
}

extend type Query {
  me: User
  getAllUsers(
    offset: Int
    limit: Int
    search: String
    sortBy: String
    sortOrder: String
  ): UserListResponse!
}

extend type Mutation {
  register(input: RegisterInput!): User!
  updateUserById(id: ID!, input: UpdateUserInput!): User!
  deleteUserById(id: ID!): User!
  login(input: LoginInput!): AuthTokens!
  refreshToken(input: RefreshTokenInput!): AuthTokens!
  logoutAllTabs: Boolean!
}
